# Generated by Django 6.0.1 on 2026-03-18 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('dgp', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=20)),
                ('cedula', models.CharField(blank=True, max_length=50)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('institucion', models.CharField(blank=True, max_length=150)),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
            ],
            options={
                'db_table': 'medicos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('expediente', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('TRABAJADOR', 'Trabajador'), ('FAMILIAR', 'Familiar'), ('PENSIONADO', 'Pensionado')], default='TRABAJADOR', max_length=20)),
                ('sexo', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'unidades_medicas',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.paciente')),
                ('unidad_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.unidadmedica')),
            ],
            options={
                'db_table': 'recetas',
            },
        ),
        migrations.CreateModel(
            name='RecetaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('dosis', models.CharField(blank=True, max_length=100)),
                ('frecuencia', models.CharField(blank=True, max_length=100)),
                ('duracion', models.CharField(blank=True, max_length=100)),
                ('indicaciones', models.CharField(max_length=255)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='recetas.receta')),
            ],
            options={
                'db_table': 'receta_detalle',
            },
        ),
    ]
