#!/usr/bin/env bash

set -eu

IS_BRANCH_CHECKOUT="${3:-0}"
if [ "$IS_BRANCH_CHECKOUT" != "1" ]; then
  exit 0
fi

ROOT_DIR="$(git rev-parse --show-toplevel)"
"$ROOT_DIR/.engram/scripts/import-on-repo-update.sh"
