# Generated by Django 6.0.4 on 2026-05-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_det_usuario_info_adicional'),
        ('catalogos', '0008_vacunas_alter_catcies_code_alter_catcies_version'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catmedico',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.RenameIndex(
            model_name='relmedicoexcepcion',
            new_name='rel_medico__medico__496bf7_idx',
            old_name='rel_med_exc_fecha_idx',
        ),
        migrations.AlterField(
            model_name='catmedico',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medico', serialize=False, to='authentication.syusuario'),
        ),
        migrations.AlterField(
            model_name='relmedicocentro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relmedicocentro',
            name='tipo_adscripcion',
            field=models.CharField(choices=[('DEFINITIVA', 'Definitiva'), ('TEMPORAL', 'Temporal')], default='DEFINITIVA', max_length=10),
        ),
        migrations.AlterField(
            model_name='relmedicocobertura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relmedicocobertura',
            name='motivo',
            field=models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('INCAPACIDAD', 'Incapacidad'), ('PERMISO', 'Permiso'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='relmedicocoberturahorario',
            name='dia_semana',
            field=models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='relmedicocoberturahorario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relmedicoconsultorio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relmedicoconsultorio',
            name='tipo_asignacion',
            field=models.CharField(choices=[('PERMANENTE', 'Permanente'), ('TEMPORAL', 'Temporal')], default='PERMANENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='relmedicoconsultoriohorario',
            name='dia_semana',
            field=models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='relmedicoconsultoriohorario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relmedicoespecialidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relmedicoexcepcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relmedicoexcepcion',
            name='tipo',
            field=models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('INCAPACIDAD', 'Incapacidad'), ('PERMISO', 'Permiso'), ('HORA_COMIDA', 'Hora de comida'), ('CAPACITACION', 'Capacitación'), ('AUSENCIA', 'Ausencia'), ('SUSPENSION', 'Suspensión'), ('CAMBIO_HORARIO', 'Cambio de horario')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='relmedicocobertura',
            index=models.Index(fields=['medico_suplente', 'fecha_inicio', 'fecha_fin'], name='rel_medico__medico__ba47af_idx'),
        ),
        migrations.AddIndex(
            model_name='relmedicocobertura',
            index=models.Index(fields=['medico_titular', 'fecha_inicio', 'fecha_fin'], name='rel_medico__medico__590a0a_idx'),
        ),
    ]
