# Generated by Django 6.0.4 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_catmedico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relmedicoconsultoriohorario',
            name='canal',
            field=models.CharField(
                choices=[('PRESENCIAL', 'Presencial'), ('LINEA', 'En línea'), ('AMBOS', 'Ambos')],
                default='PRESENCIAL',
                max_length=10,
            ),
        ),
    ]
