FROM node:20-alpine

# === CONFIGURACIÓN DE PROXY ===
ENV HTTP_PROXY=http://10.15.15.56:3128
ENV HTTPS_PROXY=http://10.15.15.56:3128
RUN npm config set proxy http://10.15.15.56:3128
RUN npm config set https-proxy http://10.15.15.56:3128
RUN npm config set strict-ssl false

WORKDIR /app

# Copiar dependencias
COPY package.json package-lock.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código fuente
COPY . .

# Exponer el puerto de Vite
EXPOSE 5173

# Comando para iniciar en modo desarrollo
CMD ["npm", "run", "dev", "--", "--host"]