# Generated by Django 6.0.4 on 2026-06-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoOxigeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=100)),
                ('num_contrato', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('expediente', models.CharField(max_length=50)),
                ('tp_der', models.CharField(blank=True, default='T', max_length=100)),
                ('clinica', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=100)),
                ('servicio_2', models.CharField(blank=True, max_length=100, null=True)),
                ('servicio_3', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('fecha_soporte', models.DateField(blank=True, null=True)),
                ('vigencia_meses', models.IntegerField(blank=True, null=True)),
                ('vigencia_dias', models.IntegerField(blank=True, null=True)),
                ('fecha_renovar', models.DateField(blank=True, null=True)),
                ('dias_faltan', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('POR_VENCER', 'Por Vencer')], default='VIGENTE', max_length=20)),
                ('diagnostico', models.CharField(blank=True, max_length=200)),
                ('fch_alta', models.DateTimeField(auto_now_add=True)),
                ('fch_modf', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrato de Oxígeno',
                'verbose_name_plural': 'Contratos de Oxígeno',
                'db_table': 'contratos_oxigeno',
                'ordering': ['num_contrato'],
            },
        ),
    ]
