# Generated by Django 6.0.4 on 2026-06-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_oxigeno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratooxigeno',
            name='alcaldia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='calle',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='colonia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='cp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='entre_calle_1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='entre_calle_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='ext_tel',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='hospital_azura',
            field=models.CharField(blank=True, choices=[('CENTRO', 'Centro'), ('VALLE', 'Valle')], max_length=10),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='institucion_referencia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='medico_tratante',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='medico_tratante_referencia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='num_ext',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='num_int',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='tel_oficina',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='tercer_nivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contratooxigeno',
            name='tramite_subsecuente',
            field=models.BooleanField(default=False),
        ),
    ]
