# Generated by Django 6.0.4 on 2026-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_oxigeno', '0002_contratooxigeno_alcaldia_contratooxigeno_calle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratooxigeno',
            name='pk_num',
            field=models.IntegerField(default=0),
        ),
    ]
