# Generated by Django 6.0.4 on 2026-06-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_oxigeno', '0003_contratooxigeno_pk_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratooxigeno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
