# Generated by Django 6.0.1 on 2026-03-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_areas_autorizadores_bajas_calidadlaboral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatCies',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('code', models.CharField(db_column='clave', max_length=8, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='descripcion', max_length=400)),
                ('version', models.CharField(db_column='version', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cat_cies',
                'managed': True,
            },
        ),
    ]
