# Generated by Django 6.0.4 on 2026-04-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_add_catcentroatencionexcepcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatCentroAtencionHorario',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_horario', primary_key=True, serialize=False)),
                ('week_day', models.SmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], db_column='dia_semana', db_index=True)),
                ('is_open', models.BooleanField(db_column='abierto', default=True)),
                ('is_24_hours', models.BooleanField(db_column='es_24_horas', default=False)),
                ('opening_time', models.TimeField(blank=True, db_column='hora_apertura', null=True)),
                ('closing_time', models.TimeField(blank=True, db_column='hora_cierre', null=True)),
                ('observations', models.CharField(blank=True, db_column='observaciones', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Horario de Centro de Atención',
                'verbose_name_plural': 'Horarios de Centros de Atención',
                'db_table': 'cat_centros_atencion_horarios',
                'ordering': ['center', 'week_day', 'shift'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='catcentroatencion',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Centro de Atención', 'verbose_name_plural': 'Centros de Atención'},
        ),
        migrations.AlterModelOptions(
            name='catcentroatencionexcepcion',
            options={'managed': True, 'ordering': ['date'], 'verbose_name': 'Excepción de Centro de Atención', 'verbose_name_plural': 'Excepciones de Centros de Atención'},
        ),
    ]
