# Generated by Django 6.0.4 on 2026-05-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_catareaclinica_centroareaclinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_vacuna', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=200)),
            ],
            options={
                'db_table': 'cat_vacunas',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='catcies',
            name='code',
            field=models.CharField(db_column='codigo', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catcies',
            name='version',
            field=models.CharField(db_column='version_cie', max_length=10),
        ),
    ]
