# Generated by Django 6.0.4 on 2026-06-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_cattipopersonal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cattipopersonal',
            old_name='fch_alta',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cattipopersonal',
            old_name='usr_alta',
            new_name='created_by_id',
        ),
        migrations.RenameField(
            model_name='cattipopersonal',
            old_name='fch_baja',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='cattipopersonal',
            old_name='usr_baja',
            new_name='deleted_by_id',
        ),
        migrations.RenameField(
            model_name='cattipopersonal',
            old_name='id_tipo_personal',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cattipopersonal',
            old_name='est_activo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='cattipopersonal',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cattipopersonal',
            old_name='fch_modf',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='cattipopersonal',
            old_name='usr_modf',
            new_name='updated_by_id',
        ),
    ]
