# Generated by Django 6.0.4 on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_rename_fch_alta_cattipopersonal_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatSucursal',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_suc', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='sucursal', max_length=100)),
            ],
            options={
                'db_table': 'cat_sucursales',
                'managed': False,
            },
        ),
    ]
