# Generated by Django 6.0.4 on 2026-07-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_catsucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catsucursal',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
    ]
