# Generated by Django 6.0.4 on 2026-08-14 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_catcies_codigo_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcentroatencionexcepcion',
            name='center',
            field=models.ForeignKey(db_column='id_centro_atencion', on_delete=django.db.models.deletion.PROTECT, related_name='excepciones', to='catalogos.catcentroatencion'),
        ),
        migrations.AlterField(
            model_name='catcentroatencionhorario',
            name='center',
            field=models.ForeignKey(db_column='id_centro_atencion', on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='catalogos.catcentroatencion'),
        ),
        migrations.AlterField(
            model_name='catcentroatencionhorario',
            name='shift',
            field=models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.PROTECT, related_name='center_schedules', to='catalogos.turnos'),
        ),
    ]
