# Generated by Django 6.0.4 on 2026-08-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0018_centro_horario_excepcion_protect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id_estudios', models.AutoField(db_column='cd_estudios', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ds_estudios', max_length=255)),
                ('precio', models.FloatField(blank=True, db_column='no_precio', null=True)),
                ('study_type', models.CharField(db_column='tp_estudios', max_length=20)),
                ('indication', models.CharField(blank=True, db_column='ds_indicacion', max_length=700, null=True)),
                ('general_flag', models.CharField(blank=True, db_column='sw_mgral', max_length=1, null=True)),
                ('authorized_flag', models.CharField(blank=True, db_column='sw_autoriza', max_length=1, null=True)),
                ('status', models.CharField(db_column='sw_status', default='1', max_length=1)),
                ('group_type', models.CharField(blank=True, db_column='tp_grupo', max_length=5, null=True)),
                ('provider_id', models.DecimalField(blank=True, db_column='id_prov', decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'cat_estudios',
                'managed': False,
            },
        ),
    ]
