# Generated by Django 6.0.4 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0018_centro_horario_excepcion_protect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacidades',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_discapacidad', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='clave_discapacidad', max_length=10)),
                ('name', models.CharField(db_column='discapacidad', max_length=300)),
            ],
            options={
                'db_table': 'cat_discapacidades',
                'managed': True,
            },
        ),
    ]
