# Generated by Django 6.0.4 on 2026-09-02

from django.db import migrations, models

SEED_MOTIVOS = [
    ("Paciente no se presentó", "NO_ASISTIO"),
    ("Cancelada por el paciente", "CANCELACION"),
    ("Cancelada por el consultorio / médico no disponible", "CANCELACION"),
    ("Reagendada", "CANCELACION"),
    ("Error de captura / duplicado", "AMBOS"),
]


def cargar_motivos_semilla(apps, schema_editor):
    MotivoCita = apps.get_model("catalogos", "MotivoCita")
    for name, aplica_a in SEED_MOTIVOS:
        MotivoCita.objects.get_or_create(name=name, defaults={"aplica_a": aplica_a})


def revertir_noop(apps, schema_editor):
    # No borramos las filas semilla al revertir: podrian estar referenciadas
    # ya desde citas_medicas/rcp_visits (FK SET_NULL evita el error, pero
    # preferimos no perder el catalogo en un rollback accidental).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0020_tipoconsulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoCita',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.AutoField(db_column='id_motivo_cita', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='motivo_cita', max_length=100)),
                ('aplica_a', models.CharField(
                    choices=[('CANCELACION', 'Cancelación'), ('NO_ASISTIO', 'No asistió'), ('AMBOS', 'Ambos')],
                    db_column='aplica_a',
                    default='AMBOS',
                    max_length=20,
                )),
            ],
            options={
                'db_table': 'cat_motivos_cita',
                'managed': True,
            },
        ),
        migrations.RunPython(cargar_motivos_semilla, revertir_noop),
    ]
