# Generated by Django 6.0.4 on 2026-09-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0021_motivos_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_religion', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='religion', max_length=45)),
            ],
            options={
                'db_table': 'cat_religion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoResidencia',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_residencia', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='residencia', max_length=45)),
            ],
            options={
                'db_table': 'cat_residencia',
                'managed': True,
            },
        ),
    ]
