# Generated by Django 6.0.4 on 2026-09-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0024_medicamentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamentos',
            options={'managed': True},
        ),
    ]
