# Generated by Django 6.0.1 on 2026-02-19 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_det_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detusuario',
            options={'verbose_name': 'Detalle Usuario', 'verbose_name_plural': 'Detalles Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='syusuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='detusuario',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalle', serialize=False, to='authentication.syusuario'),
        ),
    ]
