# Generated by Django 6.0.4 on 2026-07-13 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_detusuariocedula_tipo_free_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id_sesion', models.BigAutoField(db_column='id_sesion', primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('fch_inicio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fch_fin', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cerrada_por', models.CharField(blank=True, choices=[('LOGOUT', 'Logout'), ('EXPIRACION', 'Expiración')], max_length=10, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='authentication.syusuario')),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'db_table': 'sy_sesiones_usuario',
                'ordering': ['-fch_inicio'],
            },
        ),
    ]
