# Generated by Django 6.0.4 on 2026-08-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_sesionusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detusuario',
            name='tipo_personal',
        ),
    ]
