# Generated by Django 6.0.4 on 2026-09-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_nombre_completo_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syusuario',
            name='correo',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
