# Generated by Django 6.0.4 on 2026-09-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_syusuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detusuario',
            name='paterno',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
