# Generated by Django 6.0.1 on 2026-02-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitConsultation',
            fields=[
                ('id_consultation', models.BigAutoField(db_column='id_consultation', primary_key=True, serialize=False)),
                ('doctor_id', models.BigIntegerField(db_column='doctor_id', db_index=True)),
                ('primary_diagnosis', models.CharField(db_column='primary_diagnosis', max_length=255)),
                ('final_note', models.TextField(db_column='final_note')),
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id_visit', models.OneToOneField(db_column='id_visit', on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='recepcion.visit')),
            ],
            options={
                'db_table': 'cns_visit_consultation',
                'indexes': [models.Index(fields=['doctor_id'], name='cns_cons_doc_idx'), models.Index(fields=['is_active'], name='cns_cons_active_idx'), models.Index(fields=['created_at'], name='cns_cons_created_idx')],
            },
        ),
    ]
