# Generated by Django 6.0.1 on 2026-02-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0001_initial'),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitconsultation',
            name='doctor_id',
            field=models.BigIntegerField(db_column='id_doctor', db_index=True),
        ),
        migrations.AlterField(
            model_name='visitconsultation',
            name='final_note',
            field=models.TextField(db_column='nota_final'),
        ),
        migrations.AlterField(
            model_name='visitconsultation',
            name='id_consultation',
            field=models.BigAutoField(db_column='id_consulta', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visitconsultation',
            name='primary_diagnosis',
            field=models.CharField(db_column='diagnostico_primario', max_length=255),
        ),
    ]
