# Generated by Django 6.0.1 on 2026-02-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0002_remove_visitconsultation_cns_cons_doc_idx_and_more'),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visitconsultation',
            name='cns_cons_doc_idx',
        ),
        migrations.AddIndex(
            model_name='visitconsultation',
            index=models.Index(fields=['doctor_id'], name='cns_cons_doc_idx'),
        ),
    ]
