# Generated by Django 6.0.1 on 2026-02-24 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0003_remove_visitconsultation_cns_cons_doc_idx_and_more'),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitPrescription',
            fields=[
                ('id_prescription', models.BigAutoField(db_column='id_receta', primary_key=True, serialize=False)),
                ('items', models.JSONField(db_column='items')),
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id_visit', models.OneToOneField(db_column='id_visit', on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='recepcion.visit')),
            ],
            options={
                'db_table': 'cns_visit_prescription',
                'indexes': [models.Index(fields=['is_active'], name='cns_rx_active_idx'), models.Index(fields=['created_at'], name='cns_rx_created_idx')],
            },
        ),
    ]
