# Generated by Django 6.0.1 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consulta_medica", "0004_visitprescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitconsultation",
            name="cie_code",
            field=models.CharField(
                blank=True,
                db_column="clave_cie",
                max_length=8,
                null=True,
            ),
        ),
    ]
