# Generated by Django 6.0.4 on 2026-09-03 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0022_religion_tiporesidencia'),
        ('consulta_medica', '0008_visitconsultationrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalHistory',
            fields=[
                ('id_clinical_history', models.BigAutoField(db_column='id_historia', primary_key=True, serialize=False)),
                ('no_exp', models.CharField(db_column='no_exp', db_index=True, max_length=20)),
                ('pk_num', models.IntegerField(db_column='pk_num', default=0)),
                ('phone', models.CharField(blank=True, db_column='telefono', max_length=15, null=True)),
                ('family_history', models.TextField(blank=True, db_column='antecedentes', null=True)),
                ('current_illness', models.TextField(blank=True, db_column='padecimiento_actual', null=True)),
                ('systems_review', models.TextField(blank=True, db_column='organos_aparatos_sistemas', null=True)),
                ('head_exam', models.TextField(blank=True, db_column='exploracion_cabeza', null=True)),
                ('neck_exam', models.TextField(blank=True, db_column='exploracion_cuello', null=True)),
                ('chest_exam', models.TextField(blank=True, db_column='exploracion_torax', null=True)),
                ('abdomen_exam', models.TextField(blank=True, db_column='exploracion_abdomen', null=True)),
                ('genitals_exam', models.TextField(blank=True, db_column='exploracion_genitales', null=True)),
                ('limbs_exam', models.TextField(blank=True, db_column='exploracion_miembros', null=True)),
                ('diagnostic_management', models.TextField(blank=True, db_column='manejo_diagnostico', null=True)),
                ('therapeutic_management', models.TextField(blank=True, db_column='manejo_terapeutico', null=True)),
                ('allergies', models.TextField(blank=True, db_column='alergias', null=True)),
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('education_level', models.ForeignKey(blank=True, db_column='id_escolaridad', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.escolaridad')),
                ('marital_status', models.ForeignKey(blank=True, db_column='id_edocivil', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.edocivil')),
                ('occupation', models.ForeignKey(blank=True, db_column='id_ocupacion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.ocupaciones')),
                ('religion', models.ForeignKey(blank=True, db_column='id_religion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.religion')),
                ('residence_type', models.ForeignKey(blank=True, db_column='id_residencia', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.tiporesidencia')),
            ],
            options={
                'db_table': 'cns_clinical_history',
                'indexes': [models.Index(fields=['is_active'], name='cns_clinhist_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('no_exp', 'pk_num'), name='cns_clinhist_patient_uniq')],
            },
        ),
    ]
