# Generated by Django 6.0.4 on 2026-09-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0022_religion_tiporesidencia'),
        ('consulta_medica', '0009_clinicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalLeave',
            fields=[
                ('id_medical_leave', models.BigAutoField(db_column='id_licencia', primary_key=True, serialize=False)),
                ('no_exp', models.CharField(db_column='no_exp', db_index=True, max_length=20)),
                ('pk_num', models.IntegerField(db_column='pk_num', default=0)),
                ('is_subsequent', models.BooleanField(db_column='es_subsecuente', default=False)),
                ('days', models.PositiveSmallIntegerField(db_column='dias')),
                ('start_date', models.DateField(db_column='fecha_inicio')),
                ('end_date', models.DateField(db_column='fecha_fin')),
                ('folio', models.CharField(db_column='folio', max_length=32, unique=True)),
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('consultation', models.ForeignKey(db_column='id_consulta', on_delete=django.db.models.deletion.PROTECT, related_name='medical_leaves', to='consulta_medica.visitconsultation')),
                ('leave_type', models.ForeignKey(db_column='id_tipo_licencia', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.licencias')),
            ],
            options={
                'db_table': 'cns_medical_leave',
                'indexes': [models.Index(fields=['no_exp', 'pk_num'], name='cns_medleave_patient_idx'), models.Index(fields=['is_active'], name='cns_medleave_active_idx')],
            },
        ),
    ]
