# Generated by Django 6.0.4 on 2026-09-04 16:07

import apps.consulta_medica.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0022_religion_tiporesidencia'),
        ('consulta_medica', '0010_medicalleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyResult',
            fields=[
                ('id_study_result', models.BigAutoField(db_column='id_resultado', primary_key=True, serialize=False)),
                ('no_exp', models.CharField(db_column='no_exp', db_index=True, max_length=20)),
                ('pk_num', models.IntegerField(db_column='pk_num', default=0)),
                ('result_date', models.DateField(db_column='fecha_resultado')),
                ('notes', models.TextField(blank=True, db_column='notas', null=True)),
                ('file', models.FileField(max_length=255, upload_to=apps.consulta_medica.storage.study_result_upload_to)),
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('consultation', models.ForeignKey(db_column='id_consulta', on_delete=django.db.models.deletion.PROTECT, related_name='study_results', to='consulta_medica.visitconsultation')),
                ('study_type', models.ForeignKey(db_column='id_estudio', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.estudiosmed')),
            ],
            options={
                'db_table': 'cns_study_result',
                'indexes': [models.Index(fields=['no_exp', 'pk_num'], name='cns_studyres_patient_idx'), models.Index(fields=['is_active'], name='cns_studyres_active_idx')],
            },
        ),
    ]
