# Generated by Django 6.0.4 on 2026-09-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0011_studyresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='StomatologyHistory',
            fields=[
                ('id_stomatology_history', models.BigAutoField(db_column='id_historia_dental', primary_key=True, serialize=False)),
                ('no_exp', models.CharField(db_column='no_exp', db_index=True, max_length=20)),
                ('pk_num', models.IntegerField(db_column='pk_num', default=0)),
                ('family_diabetes', models.BooleanField(db_column='af_diabetes', default=False)),
                ('family_cancer', models.BooleanField(db_column='af_cancer', default=False)),
                ('family_high_blood_pressure', models.BooleanField(db_column='af_presion_alta', default=False)),
                ('family_low_blood_pressure', models.BooleanField(db_column='af_presion_baja', default=False)),
                ('cause_of_death', models.CharField(blank=True, db_column='causa_muerte', max_length=255, null=True)),
                ('personal_diabetes', models.BooleanField(db_column='app_diabetes', default=False)),
                ('personal_asthma', models.BooleanField(db_column='app_asma', default=False)),
                ('personal_high_blood_pressure', models.BooleanField(db_column='app_presion_alta', default=False)),
                ('personal_low_blood_pressure', models.BooleanField(db_column='app_presion_baja', default=False)),
                ('personal_hepatitis', models.BooleanField(db_column='app_hepatitis', default=False)),
                ('personal_hiv', models.BooleanField(db_column='app_vih', default=False)),
                ('personal_smoking', models.BooleanField(db_column='app_tabaquismo', default=False)),
                ('personal_alcoholism', models.BooleanField(db_column='app_alcoholismo', default=False)),
                ('personal_substance_abuse', models.BooleanField(db_column='app_toxicomanias', default=False)),
                ('habits', models.TextField(blank=True, db_column='habitos', null=True)),
                ('diet', models.TextField(blank=True, db_column='alimentacion', null=True)),
                ('surgical_history', models.TextField(blank=True, db_column='antecedentes_quirurgicos', null=True)),
                ('traumatic_history', models.TextField(blank=True, db_column='antecedentes_traumaticos', null=True)),
                ('allergy_medications', models.TextField(blank=True, db_column='alergia_medicamentos', null=True)),
                ('allergy_dental_material', models.TextField(blank=True, db_column='alergia_material_dental', null=True)),
                ('allergy_anesthesia', models.TextField(blank=True, db_column='alergia_anestesia', null=True)),
                ('allergy_food', models.TextField(blank=True, db_column='alergia_alimentos', null=True)),
                ('allergy_environment', models.TextField(blank=True, db_column='alergia_medio_ambiente', null=True)),
                ('allergy_other', models.TextField(blank=True, db_column='alergia_otros', null=True)),
                ('current_illness_history', models.TextField(blank=True, db_column='padecimiento_actual', null=True)),
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
            ],
            options={
                'db_table': 'cns_stomatology_history',
                'indexes': [models.Index(fields=['is_active'], name='cns_stomhist_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('no_exp', 'pk_num'), name='cns_stomhist_patient_uniq')],
            },
        ),
    ]
