# Generated by Django 6.0.4 on 2026-09-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0012_stomatologyhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdontogramTooth',
            fields=[
                ('id_odontogram_tooth', models.BigAutoField(db_column='id_diente', primary_key=True, serialize=False)),
                ('no_exp', models.CharField(db_column='no_exp', db_index=True, max_length=20)),
                ('pk_num', models.IntegerField(db_column='pk_num', default=0)),
                ('tooth_fdi', models.CharField(db_column='pieza_fdi', max_length=2)),
                ('condition', models.CharField(choices=[('healthy', 'Sano'), ('caries', 'Caries'), ('filled', 'Obturado'), ('crown', 'Corona'), ('missing', 'Ausente'), ('extraction_needed', 'Extracción Indicada'), ('root_canal', 'Endodoncia'), ('sealant', 'Sellante'), ('fracture', 'Fracturado'), ('implant', 'Implante')], db_column='condicion', default='healthy', max_length=32)),
                ('notes', models.CharField(blank=True, db_column='notas', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
            ],
            options={
                'db_table': 'cns_odontogram_tooth',
                'indexes': [models.Index(fields=['no_exp', 'pk_num'], name='cns_odontogram_patient_idx')],
                'constraints': [models.UniqueConstraint(fields=('no_exp', 'pk_num', 'tooth_fdi'), name='cns_odontogram_tooth_uniq')],
            },
        ),
    ]
