# Generated by Django 6.0.4 on 2026-08-24 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0019_doctor_fk_integrity'),
        ('somatometria', '0003_visitvitals_glucosa_capilar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLatestVitals',
            fields=[
                ('no_exp', models.CharField(db_column='no_exp', max_length=20, primary_key=True, serialize=False)),
                ('weight_kg', models.DecimalField(db_column='weight_kg', decimal_places=2, max_digits=6)),
                ('height_cm', models.DecimalField(db_column='height_cm', decimal_places=2, max_digits=6)),
                ('temperature_c', models.DecimalField(blank=True, db_column='temperature_c', decimal_places=1, max_digits=4, null=True)),
                ('oxygen_saturation_pct', models.PositiveSmallIntegerField(blank=True, db_column='oxygen_saturation_pct', null=True)),
                ('heart_rate_bpm', models.PositiveSmallIntegerField(blank=True, db_column='heart_rate_bpm', null=True)),
                ('respiratory_rate_bpm', models.PositiveSmallIntegerField(blank=True, db_column='respiratory_rate_bpm', null=True)),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, db_column='blood_pressure_systolic', null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, db_column='blood_pressure_diastolic', null=True)),
                ('waist_circumference_cm', models.PositiveSmallIntegerField(blank=True, db_column='waist_circumference_cm', null=True)),
                ('bmi', models.DecimalField(db_column='bmi', decimal_places=2, max_digits=6)),
                ('glucosa_capilar_mgdl', models.PositiveSmallIntegerField(blank=True, db_column='glucosa_capilar_mgdl', null=True)),
                ('fch_modf', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('id_visit_origen', models.ForeignKey(blank=True, db_column='id_visit_origen', help_text='Visita de la que vino esta ultima captura (trazabilidad del cache).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recepcion.visit')),
            ],
            options={
                'db_table': 'smt_patient_latest_vitals',
            },
        ),
    ]
