# Generated by Django 6.0.1 on 2026-02-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relrolpermiso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='relusuariooverride',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='relusuariorol',
            options={'managed': False},
        ),
    ]
