# Generated by Django 6.0.4 on 2026-07-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_relrolpermiso_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatClinica',
            fields=[
                ('cd_clinica', models.CharField(db_column='cd_clinica', max_length=10, primary_key=True, serialize=False)),
                ('ds_clinica', models.CharField(blank=True, db_column='ds_clinica', max_length=100, null=True)),
            ],
            options={
                'db_table': 'cat_clinicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatEmpleado',
            fields=[
                ('no_exp', models.CharField(db_column='no_exp', max_length=20, primary_key=True, serialize=False)),
                ('ds_paterno', models.CharField(blank=True, db_column='ds_paterno', max_length=100, null=True)),
                ('ds_materno', models.CharField(blank=True, db_column='ds_materno', max_length=100, null=True)),
                ('ds_nombre', models.CharField(blank=True, db_column='ds_nombre', max_length=100, null=True)),
                ('cd_laboral', models.CharField(blank=True, db_column='cd_laboral', max_length=100, null=True)),
                ('cve_cd_laboral', models.CharField(blank=True, db_column='cve_cd_laboral', max_length=10, null=True)),
                ('cve_baja', models.CharField(blank=True, db_column='cve_baja', max_length=10, null=True)),
                ('fec_baja', models.DateField(blank=True, db_column='fec_baja', null=True)),
                ('fe_nac', models.DateField(blank=True, db_column='fe_nac', null=True)),
                ('fec_vig', models.DateField(blank=True, db_column='fec_vig', null=True)),
                ('no_edad', models.IntegerField(blank=True, db_column='no_edad', null=True)),
                ('cd_clinica', models.CharField(blank=True, db_column='cd_clinica', max_length=10, null=True)),
                ('fec_ult_actualizacion', models.DateTimeField(blank=True, db_column='fec_ult_actualizacion', null=True)),
            ],
            options={
                'db_table': 'cat_empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatFamiliar',
            fields=[
                ('pk_num', models.IntegerField(db_column='pk_num', primary_key=True, serialize=False)),
                ('no_expf', models.CharField(db_column='no_expf', max_length=20)),
                ('ds_paterno', models.CharField(blank=True, db_column='ds_paterno', max_length=100, null=True)),
                ('ds_materno', models.CharField(blank=True, db_column='ds_materno', max_length=100, null=True)),
                ('ds_nombre', models.CharField(blank=True, db_column='ds_nombre', max_length=100, null=True)),
                ('cd_parentesco', models.CharField(blank=True, db_column='cd_parentesco', max_length=50, null=True)),
                ('tp_der', models.CharField(blank=True, db_column='tp_der', max_length=2, null=True)),
                ('fe_nac', models.DateField(blank=True, db_column='fe_nac', null=True)),
                ('no_edad', models.IntegerField(blank=True, db_column='no_edad', null=True)),
                ('fec_vig', models.DateField(blank=True, db_column='fec_vig', null=True)),
                ('cd_clinica', models.CharField(blank=True, db_column='cd_clinica', max_length=10, null=True)),
                ('fec_ult_actualizacion', models.DateTimeField(blank=True, db_column='fec_ult_actualizacion', null=True)),
            ],
            options={
                'db_table': 'cat_familiar',
                'managed': False,
            },
        ),
    ]
