# Generated by Django 6.0.4 on 2026-08-18 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_catclinica_catempleado_catfamiliar'),
        ('catalogos', '0018_centro_horario_excepcion_protect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.BigAutoField(db_column='id_modulo', primary_key=True, serialize=False)),
                ('clave', models.CharField(db_column='clave', max_length=160, unique=True)),
                ('titulo', models.CharField(db_column='titulo', max_length=120)),
                ('icono', models.CharField(blank=True, db_column='icono', max_length=60, null=True)),
                ('url', models.CharField(blank=True, db_column='url', max_length=255, null=True)),
                ('badge', models.CharField(blank=True, db_column='badge', max_length=30, null=True)),
                ('orden', models.IntegerField(db_column='orden', default=0)),
                ('es_seccion', models.BooleanField(db_column='es_seccion', default=False)),
                ('grupo', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], db_column='grupo', default='primary', max_length=20)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('fch_alta', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('fch_modf', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('fch_baja', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('id_parent', models.ForeignKey(blank=True, db_column='id_parent', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='administracion.modulo')),
            ],
            options={
                'db_table': 'cat_modulos',
                'ordering': ['orden', 'titulo'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModuloPermiso',
            fields=[
                ('id_modulo_permiso', models.BigAutoField(db_column='id_modulo_permiso', primary_key=True, serialize=False)),
                ('id_modulo', models.ForeignKey(db_column='id_modulo', on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='administracion.modulo')),
                ('id_permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.PROTECT, related_name='modulos', to='catalogos.permisos')),
            ],
            options={
                'db_table': 'rel_modulo_permisos',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='modulo',
            index=models.Index(fields=['id_parent', 'orden'], name='cat_modulos_parent_orden_idx'),
        ),
        migrations.AddIndex(
            model_name='modulo',
            index=models.Index(fields=['grupo', 'es_seccion', 'orden'], name='cat_modulos_grp_secc_ord_idx'),
        ),
        migrations.AddConstraint(
            model_name='modulo',
            constraint=models.CheckConstraint(condition=models.Q(('id_parent', models.F('id_modulo')), _negated=True), name='cat_modulos_no_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='modulopermiso',
            constraint=models.UniqueConstraint(fields=('id_modulo', 'id_permiso'), name='rel_modulo_permiso_unique'),
        ),
    ]
