# Generated by Django 6.0.4 on 2026-08-21 00:17

from django.db import migrations, models

# Literal CONGELADO al momento de escribir esta migración -- a propósito NO
# importa `CLAVES_SISTEMA` desde `apps.administracion.management.seeds.
# navigation_seed` (las migraciones no deben depender de código de la app
# que puede cambiar con el tiempo; ver Django docs sobre RunPython y
# "historical models"). Debe coincidir con `CLAVES_SISTEMA` al momento de
# este commit; si diverge en el futuro no pasa nada -- esta migración corre
# una única vez sobre datos existentes, y `seed_navigation_menu` reafirma el
# estado correcto en cada corrida contra la lista viva.
CLAVES_SISTEMA_0005 = frozenset(
    {
        "administracion",
        "clinico",
        "recepcion",
        "farmacia",
        "almacen",
        "servicios",
        "core",
        "administracion.panel",
        "administracion.panel.roles",
        "administracion.panel.usuarios",
    }
)


def marcar_es_sistema(apps, schema_editor):
    """Marca es_sistema=True (y reactiva is_active=True) en las claves
    críticas listadas en CLAVES_SISTEMA_0005, si ya existen sembradas."""
    Modulo = apps.get_model("administracion", "Modulo")
    Modulo.objects.filter(clave__in=CLAVES_SISTEMA_0005).update(
        es_sistema=True, is_active=True
    )


def revertir_es_sistema(apps, schema_editor):
    """Reverse no-op funcional: vuelve es_sistema a False en esas mismas
    claves, por convención de reversibilidad. No restaura is_active (esa
    reactivación no tiene una contraparte lógica de "estado anterior" -- si
    alguna de estas filas estaba is_active=False antes de aplicar esta
    migración, revertir no la vuelve a desactivar)."""
    Modulo = apps.get_model("administracion", "Modulo")
    Modulo.objects.filter(clave__in=CLAVES_SISTEMA_0005).update(es_sistema=False)


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_modulo_modulopermiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='es_sistema',
            field=models.BooleanField(db_column='es_sistema', default=False),
        ),
        migrations.RunPython(marcar_es_sistema, revertir_es_sistema),
    ]
