# Generated by Django 6.0.4 on 2026-05-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_det_usuario_info_adicional'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detusuarioadministrativo',
            options={'verbose_name': 'Perfil Administrativo', 'verbose_name_plural': 'Perfiles Administrativos'},
        ),
        migrations.AlterModelOptions(
            name='detusuarioenfermeria',
            options={'verbose_name': 'Perfil Enfermería', 'verbose_name_plural': 'Perfiles Enfermería'},
        ),
        migrations.AlterModelOptions(
            name='detusuariomedico',
            options={'verbose_name': 'Perfil Médico', 'verbose_name_plural': 'Perfiles Médicos'},
        ),
        migrations.AlterField(
            model_name='detusuarioadministrativo',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_administrativo', serialize=False, to='authentication.syusuario'),
        ),
        migrations.AlterField(
            model_name='detusuarioenfermeria',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_enfermeria', serialize=False, to='authentication.syusuario'),
        ),
        migrations.AlterField(
            model_name='detusuariomedico',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_medico', serialize=False, to='authentication.syusuario'),
        ),
    ]
