# Generated by Django 6.0.4 on 2026-08-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacInventario',
            fields=[
                ('id', models.BigAutoField(db_column='id_inventario', primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField(db_column='cantidad_existencia', default=0)),
                ('applied_doses', models.IntegerField(db_column='dosis_aplicadas', default=0)),
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='fch_alta', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
            ],
            options={
                'db_table': 'vac_inventario',
                'managed': False,
            },
        ),
    ]
