# Generated by Django 6.0.4 on 2026-07-29
"""
Fase 1 del módulo "Citas en Línea": modelo de datos del portal de
autoservicio (PortalMiembro, PortalSesion, PortalOTP). Todas las tablas
son managed=True — Django las crea y administra, a diferencia de los
catálogos replicados desde Oracle (managed=False).
"""

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalMiembro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no_exp', models.CharField(db_index=True, max_length=20)),
                ('pk_num', models.IntegerField(default=0)),
                ('nombre_visible', models.CharField(max_length=150)),
                ('es_titular_login', models.BooleanField(default=False)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('correo_verificado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portal_miembros',
                'indexes': [models.Index(fields=['no_exp', 'pk_num'], name='portal_miembro_noexp_pknum_idx')],
                'unique_together': {('no_exp', 'pk_num')},
            },
        ),
        migrations.CreateModel(
            name='PortalSesion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('revocado', models.BooleanField(default=False)),
                ('portal_miembro', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sesiones',
                    to='portal_citas.portalmiembro',
                )),
            ],
            options={
                'db_table': 'portal_sesiones',
                'indexes': [
                    models.Index(fields=['portal_miembro', 'revocado'], name='portal_sesion_miembro_rev_idx'),
                    models.Index(fields=['expira_en'], name='portal_sesion_expira_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='PortalOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_destino', models.EmailField(max_length=254)),
                ('codigo_hash', models.CharField(max_length=255)),
                ('expira_en', models.DateTimeField()),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('portal_miembro', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='otps',
                    to='portal_citas.portalmiembro',
                )),
            ],
            options={
                'db_table': 'portal_otps',
                'indexes': [models.Index(fields=['correo_destino', 'usado'], name='portal_otp_correo_usado_idx')],
            },
        ),
    ]
