class RBACActions:

    ROLE_CREATE = "RBAC_ROLE_CREATE"
    ROLE_UPDATE = "RBAC_ROLE_UPDATE"
    ROLE_DELETE = "RBAC_ROLE_DELETE"
    ROLE_LIST = "RBAC_ROLE_LIST"

    USER_ROLE_ASSIGN = "RBAC_USER_ROLES_ASSIGN"
    USER_ROLE_PRIMARY = "RBAC_USER_ROLE_PRIMARY_SET"
