# Generated by Django 6.0.1 on 2026-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id_visit', models.BigAutoField(db_column='id_visit', primary_key=True, serialize=False)),
                ('folio', models.CharField(db_column='folio', max_length=32, unique=True)),
                ('patient_id', models.BigIntegerField(db_column='patient_id', db_index=True)),
                ('arrival_type', models.CharField(choices=[('appointment', 'appointment'), ('walk_in', 'walk_in')], db_column='arrival_type', max_length=16)),
                ('appointment_id', models.CharField(blank=True, db_column='appointment_id', max_length=64, null=True)),
                ('doctor_id', models.BigIntegerField(blank=True, db_column='doctor_id', db_index=True, null=True)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=255, null=True)),
                ('status', models.CharField(db_column='status', db_index=True, max_length=32)),
                ('fch_alta', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('fch_modf', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('fch_baja', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
            ],
            options={
                'db_table': 'rcp_visits',
                'indexes': [models.Index(fields=['doctor_id', 'status'], name='rcp_visits_doc_status_idx'), models.Index(fields=['fch_alta'], name='rcp_visits_fch_alta_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('arrival_type', 'appointment'), ('appointment_id__isnull', False), models.Q(('appointment_id', ''), _negated=True)), models.Q(('arrival_type', 'walk_in'), models.Q(('appointment_id__isnull', True), ('appointment_id', ''), _connector='OR')), _connector='OR'), name='rcp_visits_arrival_appointment_ck')],
            },
        ),
    ]
