# Generated by Django 6.0.1 on 2026-04-06 22:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_visit_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_paciente', models.CharField(choices=[('trabajador', 'Trabajador'), ('derechohabiente', 'Derechohabiente')], db_index=True, max_length=20)),
                ('no_exp', models.IntegerField(db_index=True)),
                ('pk_num', models.IntegerField(db_index=True, default=0)),
                ('medico_id', models.IntegerField(db_index=True)),
                ('centro_atencion_id', models.BigIntegerField(db_index=True)),
                ('consultorio_id', models.BigIntegerField(db_index=True)),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('estatus', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('atendida', 'Atendida'), ('no_asistio', 'No asistió')], db_index=True, default='agendada', max_length=20)),
                ('motivo', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('nombre_paciente', models.CharField(max_length=250)),
                ('nombre_medico', models.CharField(blank=True, default='', max_length=250)),
                ('nombre_centro', models.CharField(blank=True, default='', max_length=250)),
                ('nombre_consult', models.CharField(blank=True, default='', max_length=100)),
                ('creado_por', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'citas_medicas',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['no_exp', 'pk_num'], name='cita_paciente_idx'), models.Index(fields=['medico_id', 'fecha_hora'], name='cita_medico_dt_idx'), models.Index(fields=['consultorio_id', 'fecha_hora'], name='cita_consult_dt_idx'), models.Index(fields=['estatus', 'fecha_hora'], name='cita_estatus_dt_idx'), models.Index(fields=['centro_atencion_id', 'fecha_hora'], name='cita_centro_dt_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estatus', 'cancelada'), _negated=True), fields=('no_exp', 'pk_num', 'medico_id', 'fecha_hora'), name='unique_cita_paciente_medico'), models.UniqueConstraint(condition=models.Q(('estatus', 'cancelada'), _negated=True), fields=('consultorio_id', 'fecha_hora'), name='unique_cita_consultorio_dt'), models.UniqueConstraint(condition=models.Q(('estatus', 'cancelada'), _negated=True), fields=('medico_id', 'fecha_hora'), name='unique_cita_medico_dt')],
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('medico_id', models.IntegerField(db_index=True)),
                ('consultorio_id', models.BigIntegerField(db_index=True)),
                ('centro_atencion_id', models.BigIntegerField(db_index=True)),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('disponible', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'horarios_disponibles',
                'indexes': [models.Index(fields=['medico_id', 'disponible', 'fecha_hora'], name='horario_med_disp_idx'), models.Index(fields=['consultorio_id', 'fecha_hora'], name='horario_consult_dt_idx'), models.Index(fields=['centro_atencion_id', 'fecha_hora'], name='horario_centro_dt_idx')],
                'constraints': [models.UniqueConstraint(fields=('medico_id', 'fecha_hora'), name='unique_horario_medico_fecha')],
            },
        ),
        migrations.CreateModel(
            name='CitaNotificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('confirmacion', 'Confirmación de cita'), ('recordatorio', 'Recordatorio 24h'), ('cancelacion', 'Cancelación'), ('token_confirm', 'Token confirmación asistencia')], db_index=True, max_length=20)),
                ('email_destino', models.EmailField(max_length=254)),
                ('enviado', models.BooleanField(db_index=True, default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('token_usado', models.BooleanField(db_index=True, default=False)),
                ('token_expira', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='recepcion.citamedica')),
            ],
            options={
                'db_table': 'citas_notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cita', 'tipo'], name='notif_cita_tipo_idx'), models.Index(fields=['enviado', 'created_at'], name='notif_envio_idx')],
            },
        ),
    ]
