# Generated by Django 6.0.4 on 2026-05-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_visit_service_type'),
        ('recepcion', '0008_remove_visit_patient_id'),
    ]

    operations = [
    ]
