# Generated by Django 6.0.4 on 2026-05-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_vacunas_alter_catcies_code_alter_catcies_version'),
        ('medicos', '0002_alter_catmedico_options_and_more'),
        ('recepcion', '0011_visit_num_ficha_turno_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='citanotificacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='horariodisponible',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='turnofichaconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['consultorio'], name='citas_consultorio_idx'),
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['medico', 'estatus', 'fecha_hora'], name='citas_medico_estatus_fecha_idx'),
        ),
    ]
