# Generated by Django 6.0.4 on 2026-05-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0012_alter_citamedica_id_alter_citanotificacion_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='citamedica',
            table='"sires"."citas_medicas"',
        ),
    ]
