# Generated by Django 6.0.4 on 2026-05-25 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0013_alter_citamedica_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='created_by_id',
            field=models.BigIntegerField(blank=True, db_column='created_by_id', null=True),
        ),
        migrations.CreateModel(
            name='VisitStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, db_column='from_status', max_length=32, null=True)),
                ('to_status', models.CharField(db_column='to_status', max_length=32)),
                ('changed_by_id', models.BigIntegerField(blank=True, db_column='changed_by_id', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_column='changed_at')),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=255, null=True)),
                ('visit', models.ForeignKey(db_column='visit_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='recepcion.visit')),
            ],
            options={
                'db_table': 'rcp_visit_status_log',
                'ordering': ['changed_at'],
            },
        ),
    ]
