# Generated by Django 6.0.4 on 2026-05-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0014_add_created_by_and_status_log'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visitstatuslog',
            table='"sires"."rcp_visit_status_log"',
        ),
    ]
