# Generated by Django 6.0.4 on 2026-07-29
"""
Fase 1 del módulo "Citas en Línea" (portal de autoservicio):
  - HorarioDisponible.canal   -> canal por el que el slot está habilitado
                                 (se copia desde RelMedicoConsultorioHorario.canal
                                 al generar el slot; lógica de una fase posterior).
  - CitaMedica.origen_canal / verificado_en / verificado_por_id /
    cancelado_en / cancelado_por_id / motivo_cancelacion
                                -> trazabilidad de citas agendadas/canceladas
                                   desde el portal.
  - CitaNotificacion.tipo     -> se agregan los choices "comprobante_portal"
                                 y "cancelacion" sin quitar los existentes.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0016_visit_fecha_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodisponible',
            name='canal',
            field=models.CharField(
                choices=[('PRESENCIAL', 'Presencial'), ('LINEA', 'En línea'), ('AMBOS', 'Ambos')],
                default='PRESENCIAL',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='origen_canal',
            field=models.CharField(
                choices=[('RECEPCION', 'Recepción'), ('PORTAL', 'Portal')],
                default='RECEPCION',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='verificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='verificado_por_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='cancelado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='cancelado_por_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citanotificacion',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('confirmacion', 'Confirmación'),
                    ('recordatorio', 'Recordatorio'),
                    ('comprobante_portal', 'Comprobante portal'),
                    ('cancelacion', 'Cancelación'),
                ],
                max_length=20,
            ),
        ),
    ]
