# Generated by Django 6.0.4 on 2026-07-31
"""
Portal de Citas — disponibilidad por consultorio:

Agrega índice compuesto (consultorio, fecha, canal) a
``HorarioDisponible`` para soportar el filtro de slots por consultorio y
la agregación mensual de disponibilidad (``fecha__range`` vía
``calendar.monthrange``, NUNCA ``fecha__year``/``fecha__month`` porque
eso envuelve la columna en ``EXTRACT()`` e inutiliza el índice).

No destructiva: solo agrega un índice, no toca datos ni columnas. Se
revierte con ``migrate recepcion 0017``.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0017_portal_citas_fase1_campos'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='horariodisponible',
            index=models.Index(
                fields=['consultorio', 'fecha', 'canal'],
                name='hd_consult_fecha_canal_idx',
            ),
        ),
    ]
