# Generated by Django 6.0.4 on 2026-09-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0022_visit_tipo_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, db_column='motivo_cancelacion', null=True),
        ),
    ]
